name: Auto Tag Merges

on:
  push:
    branches:
      - main

jobs:
  tag-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo with tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get list of changed subfolders
        id: folders
        run: |
          # Get second-level folder names (e.g., script1 from brew-scripts/script1/file.sh)
          changed_folders=$(git diff --name-only HEAD^ HEAD | awk -F/ 'NF>=2 {print $2}' | sort -u)
          echo "Changed folders: $changed_folders"
          echo "FOLDERS=$changed_folders" >> $GITHUB_ENV

      - name: Tag each changed folder
        run: |
          for folder in $FOLDERS; do
            if [ -d "$folder" ]; then
              echo "Processing folder: $folder"

              # Find latest tag for this folder in format vX.Y.Z
              latest_tag=$(git tag --list "v*" | grep "^v[0-9]*\.[0-9]*\.[0-9]*$" | grep "$folder" | sort -V | tail -n 1)

              if [[ "$latest_tag" =~ v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
                major="${BASH_REMATCH[1]}"
                minor="${BASH_REMATCH[2]}"
                patch="${BASH_REMATCH[3]}"
                new_patch=$((patch + 1))
                new_version="v${major}.${minor}.${new_patch}"
              else
                new_version="v1.0.0"
              fi

              echo "Creating tag: $new_version for folder $folder"

              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git tag "$folder/$new_version"
              git push origin "$folder/$new_version"
            else
              echo "Skipping $folder (not a directory)"
            fi
          done
