name: Auto Tag Merges

on:
  push:
    branches:
      - main

jobs:
  tag-folders:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full repo with tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get list of changed subfolders
        id: folders
        run: |
          # Get full path of second-level folders (e.g., brew-scripts/telehelper)
          changed_folders=$(git diff --name-only HEAD^ HEAD | awk -F/ '{print $1 "/" $2}' | grep -v '^/' | sort -u)
          echo "Changed folders: $changed_folders"
          echo "FOLDERS=$changed_folders" >> $GITHUB_ENV

      - name: Tag each changed folder
        run: |
          for folder_path in $FOLDERS; do
            if [ -d "$folder_path" ]; then
              folder=$(basename "$folder_path")
              echo "Processing folder: $folder"

              # Find latest tag in the format vX.Y.Z for this folder
              latest_tag=$(git tag --list "$folder-v*" | sort -V | tail -n 1)

              if [[ "$latest_tag" =~ v([0-9]+)\.([0-9]+)\.([0-9]+) ]]; then
                major="${BASH_REMATCH[1]}"
                minor="${BASH_REMATCH[2]}"
                patch="${BASH_REMATCH[3]}"
                new_patch=$((patch + 1))
                new_version="v${major}.${minor}.${new_patch}"
              else
                new_version="v1.0.0"
              fi

              echo "Creating tag: $folder-$new_version"

              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"
              git tag "$folder/$new_version"
              git push origin "$folder/$new_version"
            else
              echo "Skipping $folder_path (not a directory)"
            fi
          done
